---
title: "Taller_Final"
output: pdf_document
date: "2024-10-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Desarrollo del taller


```{r}
valores  = unique(muestra$ESTU_TIPODOCUMENTO)

n = nrow(muestra)

for (valor in valores) {
  x = sum(muestra$ESTU_TIPODOCUMENTO == valor)
}

resultado = prop.test(x = x , n = n, conf.level = 0.95)

cat("n\ Tipo de documento:" , valor)

print(resultado)
```

Segunda variable categórica (ESTU_NACIONALIDAD)

```{r}
valores = unique(muestra$ESTU_NACIONALIDAD)
n = nrow(muestra)

for (valor in valores) {
  x = sum(muestra$ESTU_NACIONALIDAD == valor)
  
  # Realizamos la prueba de proporción para cada nacionalidad contra 0.5
  resultado = prop.test(x = x, n = n, p = 0.5, conf.level = 0.95)
  
  # Mostramos los resultados con print
  print(paste("Nacionalidad:", valor))
  print(resultado)
}
```

IC de columna GENERO
```{r}
valores = unique(muestra$ESTU_GENERO)
n = nrow(muestra)

for (valor in valores){
  x = sum(muestra$ESTU_GENERO == valor)
  
  resultado = prop.test(x = x, n = n, p = 0.5, conf.level = 0.95)

print(paste("Genero:",valor))
print(resultado)
  
}
```

IC para Puntaje de inglés

```{r}


#chisq.test(muestra$PUNT_INGLES)
Li2 = (n-1) * var(muestra$PUNT_INGLES)/qchisq(0.025, n-1, lower.tail = F)
Ls2 = (n-1) * var(muestra$PUNT_INGLES)/qchisq(0.025, n-1, lower.tail = T)

sqrt(Li2)
sqrt(Ls2)
```

IC Para periodo
```{r}

valores = unique(muestra$ESTU_PAIS_RESIDE)
n = nrow(muestra)

for (valor in valores) {
    resultado = prop.test(x = x, n = n, p = 0.5, conf.level = 0.95)

print(paste("País residencia:",valor))
print(resultado) 
} 


```

IC DE MUNICIPIO DE RESIDENCIAS

```{r}

valores = unique(muestra$ESTU_DEPTO_RESIDE)
n = nrow(muestra)

for (valor in valores) {
  x = sum(muestra$ESTU_DEPTO_RESIDE == valor)
  
  resultado = prop.test(x = x, n = n, p = 0.5, conf.level = 0.95)

  print(paste("Departamento:", valor))
  print(resultado)
}


```

IC para Estrato de vivienda

```{r}

valores = unique(muestra$FAMI_ESTRATOVIVIENDA)
n = nrow(muestra)

for (valor in valores){
    x = sum(muestra$FAMI_ESTRATOVIVIENDA == valor)
    resultado = prop.test(x = x, n = n, p = 0.5, conf.level = 0.95)
  print(paste("Estrato:", valor))
  print(resultado)
}

```

IC para Cantidad de personas en la familia

```{r}

valores = unique(muestra$FAMI_PERSONASHOGAR)
n = nrow(muestra)

for (valor in valores){
  x = sum(muestra$FAMI_PERSONASHOGAR == valor)
  resultado = prop.test(x = x, n = n, p = 0.5 , conf.level = 0.95)
  
  print(paste("Personas por hogar", valor))
  print(resultado)
  
}

```

IC para cantidad de cuartos en sus hogares
```{r}
valores = unique(muestra$FAMI_CUARTOSHOGAR)
n = nrow(muestra)

for (valor in valores){
  x = sum(muestra$FAMI_CUARTOSHOGAR == valor)
  resultado = prop.test(x = x, n = n, p = 0.5, conf.level = 0.95 )
  print(paste("Cantidad de cuartos", valor))
  print(resultado)
  
}

```
IC para puntaje en lectura crítica

```{r lectura_critica}

chisq.test(muestra$PUNT_LECTURA_CRITICA)
Li2 = (n-1) * var(muestra$PUNT_LECTURA_CRITICA)/qchisq(0.025, n-1, lower.tail = F)
Ls2 = (n-1) * var(muestra$PUNT_LECTURA_CRITICA)/qchisq(0.025, n-1, lower.tail = T)

sqrt(Li2)
sqrt(Ls2)

Lectura = t.test(muestra$PUNT_LECTURA_CRITICA, conf.level = 0.95)


print(Lectura)




```
